project:
  type: book
  output-dir: docs

book:
  title: "mishmash"
  author: "Yair Mau"
  # date: "4/9/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



